### PR TITLE
Don't install all optional components

### PR DESCRIPTION
**Pull request by fkorotkov**

### CODE REVIEW

**Comment by fkorotkov** [comment]
@k0ekk0ek do we need all the `includeOptional`? Or maybe select just a few. It seems the layer becomes too large for Docker Hub to push.

**Comment by fkorotkov** [comment]
@k0ekk0ek what do you think about not including all optional packages?

**Comment by k0ekk0ek** [comment]
I can live without the optional components for a while, but I'd prefer to be able to target 2017 and 2015 too. Also, #16 needs some optional component (or `visualstudio2019-workload-nativedesktop`, but you shouldn't install that with the `visualstudio2019-buildtools` package). I think the real solution here is to use the Visual Studio installer directly rather than the Chocolatey package, which allows you to install without caches (`--nocache`) etc, hopefully resulting in a smaller Docker image (https://jfreeman.dev/blog/2019/07/09/what-i-learned-making-a-docker-container-for-building-c++-on-windows/). Also, the .NET 4.8 SDK recipes can be found in Microsoft's GitHub, which show how to properly cleanup after installation. Shouldn't be too much work now that the base image is good (I tried that before using the Chocolatey method, not removing the temporary directory, which was part of my latest PR, made that work without any issues). However, I don't currently have a lot of time to burn on this. Alternatively, if the @ericoporto can indicate exactly which component is required (it must be one that's in recommended for `visualstudio2019-workload-nativedesktop` and optional for `visualstudio2019-workload-vctools`), we could try to just install that component and add the necessary [Visual Studio workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019) for VS2015 (`Microsoft.VisualStudio.Component.VC.140`) and VS2017 (`Microsoft.VisualStudio.Component.VC.v141.x86.x64`) using `--add <component ID>`, which should save tons of space.

It should go without saying that the above is what I think a Visual Studio build environment should offer. If you're fine with supporting 2019 only (which is already very usable and much appreciated btw :slightly_smiling_face:), I'm completely fine with that too.

**Comment by ericoporto** [comment]
About my other PR after burning a lot of brain (and hard drive running a lot of docker commands) I concluded the problem wasn't with the Windows image here, and instead with Microsoft. I install the cpp build tools for VS 2015 and they should suffice to build vcpkg, but they don't - making what is written in their readme invalid. Because the change here happened in the same tag I had no way to easily boot the previous image to verify it. So in the end I don't think I care as much about what is in the image itself as long that once change happens, it's in a new tag and I can run the previous tag.

This is because if I wanted to skip the base image from cirrus and instead use one of my own or some from Microsoft I actually can't because pulling the image takes a lot of time. So if the tags had versions, even if I could not pull the previous tags on Cirrus, I would be able to pull on my machine (since they are pushed to Dockerhub) and locally verify why things got broken. 

For now I simply moved away from Vcpkg because it was the only thing I had in my CI that wasn't versioned - except for the Cirrus-CI Windows Docker base image. Now if things break on the future at least I can know the problem is here. But previous bug was not, it was Microsoft. I reopened the ticket there and tracked a bunch other issues in their repo with people with the same problem as I.

**Comment by k0ekk0ek** [comment]
In that case @fkorotkov, can you try replacing `--includeOptional` with `--add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.VC.v141.x86.x64`? That way users can target 2019, 2017 and 2015 while the image size is kept fairly small.

**Comment by fkorotkov** [comment]
Added. @k0ekk0ek, will this change work for you now?

**Comment by k0ekk0ek** [comment]
Looks good @fkorotkov! [This test build](https://cirrus-ci.com/build/6519857359355904) should pass if this is everything required, which I think it is, but it seems with Visual Studio you never know... :slightly_smiling_face:

**Comment by fkorotkov** [comment]
Doesn't seem to help 😪

**Comment by k0ekk0ek** [comment]
Spotted it. Seems to be the version flag from the looks of it. Best option is probably to use the Visual Studio installer directly. I don't have much time available to work on it right now, but I'll give it a go in the coming weeks. Thanks for the excellent help @fkorotkov! :+1:

**Comment by fkorotkov** [comment]
I need to thank you for all the help! Our team has very limited Windows knowledge and you help is greatly appreciated!

**Pull request merged**
